# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    self.driver.get("https://officemanager.dodopizza.ru/OfficeManager/Debiting/PrepareExcelReport")
    self.driver.set_window_size(1440, 774)
    self.driver.find_element(By.ID, "StartDate").click()
    self.driver.find_element(By.LINK_TEXT, "1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.ID, "EndDate").click()
    self.driver.find_element(By.LINK_TEXT, "5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) .CaptionCont i").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open li:nth-child(1) i").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(1) .CaptionCont i").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open > .select-all > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".open > .select-all i").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.NAME, "reportButton").click()
  
